export const SAGA_GLUCOSE_LIST = 'SAGA_GLUCOSE_LIST'
export const SAGA_SET_GLUCOSE = 'SAGA_SET_GLUCOSE'

export const FETCH_GLUCOSE_LIST = 'FETCH_GLUCOSE_LIST'
export const FETCH_CURRENT_GLUCOSE = 'FETCH_CURRENT_GLUCOSE'

export const SHOW_SET_GLUCOSE_MODAL = 'SHOW_SET_GLUCOSE_MODAL'
export const HIDE_SET_GLUCOSE_MODAL = 'HIDE_SET_GLUCOSE_MODAL'
