export const SAGA_MEDICAMENT_LIST = 'SAGA_MEDICAMENT_LIST'
export const SAGA_CREATE_MEDICAMENT = 'SAGA_CREATE_MEDICAMENT'
export const SAGA_EDIT_MEDICAMENT = 'SAGA_EDIT_MEDICAMENT'
export const SAGA_DELETE_MEDICAMENT = 'SAGA_DELETE_MEDICAMENT'
export const SAGA_ADD_MEDICAMENT = 'SAGA_ADD_MEDICAMENT'

export const FETCH_MEDICAMENT_LIST = 'FETCH_MEDICAMENT_LIST'
export const FETCH_CURRENT_MEDICAMENT = 'FETCH_CURRENT_MEDICAMENT'

export const SHOW_CREATE_MEDICAMENT_MODAL = 'SHOW_CREATE_MEDICAMENT_MODAL'
export const HIDE_CREATE_MEDICAMENT_MODAL = 'HIDE_CREATE_MEDICAMENT_MODAL'

export const SHOW_EDIT_MEDICAMENT_MODAL = 'SHOW_EDIT_MEDICAMENT_MODAL'
export const HIDE_EDIT_MEDICAMENT_MODAL = 'HIDE_EDIT_MEDICAMENT_MODAL'

export const SHOW_ADD_MEDICAMENT_MODAL = 'SHOW_ADD_MEDICAMENT_MODAL'
export const HIDE_ADD_MEDICAMENT_MODAL = 'HIDE_ADD_MEDICAMENT_MODAL'
